### ISSUE TITLE
Missing Travis

### ISSUE THREAD

**Issue by PurpleBooth** [UKHomeOffice/vault-sidekick#2]

**Comment by gambol99** [comment]
there's a .travis.yml in the repo??

```YAML
language: go
go:
  - 1.4
  - 1.5
install:
  - make test
```
