### ISSUE TITLE
Recommend secrets volume be tmpfs?

### ISSUE THREAD

**Issue by jpap** [UKHomeOffice/vault-sidekick#33]
In the [example deployment configuration](https://github.com/UKHomeOffice/vault-sidekick/blob/master/examples/deployment.yaml), would it be better to specify that the `emptyDir` volume medium to be `Memory` so that secrets aren't written to disk?

The configuration would then become:
```
     ...
     volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
```
